image:
  name: registry.gitlab.com/ptl-website/jekyll-builder:latest

stages:
  - check
  - deploy

variables:
  JEKYLL_ENV: production

check:
  stage: check

  script:
    - bundle exec jekyll clean --source website
    - bundle exec jekyll build \
        --source website \
        --destination public

pages:
  stage: deploy

  script:
    - bundle exec jekyll clean --source website
    - bundle exec jekyll build \
        --source website \
        --destination public

  artifacts:
    paths:
      - public

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'