image:
  name: registry.gitlab.com/ptl-website/jekyll-builder:latest

stages:
  - check
  - deploy

variables:
  JEKYLL_ENV: production

check:
  stage: check
  script:
    - cd website
    - bundle exec jekyll clean --destination ../public
    - bundle exec jekyll build --destination ../public

pages:
  stage: deploy
  script:
    - cd website
    - bundle exec jekyll clean --destination ../public
    - bundle exec jekyll build --destination ../public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'