title: PTL-Jekyll
email: info@pathway-technologies.com

description: >-
  Engineering for safety-critical and regulated systems.
  Specialising in functional safety, DevOps, compliance,
  training, and deterministic document workflows.

baseurl: ""

url: "https://jekyll.ptl-cloud.com/"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  load_paths:
    - _sass

defaults:
  -
    scope:
      path: ""
    values:
      banner-show: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - README.md
